config/routes.rb
Rails.application.routes.draw do
  

  root 'welcome#index'

  resources :characters
  resources :matches
  
  post '/webcalls/record_match' => 'webcalls#record_match'
  post '/webcalls/current_match' => 'webcalls#current_match'
  post '/matchup/get_matchup' => 'matchup#get_matchup'
  
  get 'matchup/autocomplete_character_name'
  resources :matchup 
  

end

app/controllers/matchup_controller.rb
class MatchupController < ApplicationController
  autocomplete :character, :name
  
  def index
  end
  
  def show
  end
  
  def get_matchup
    @player1_name = params[:player1]
    @player2_name = params[:player2]
    @player1 = Character.find_by_name(@player1_name)
    @player2 = Character.find_by_name(@player2_name)
    @player1_matchup_data = @player1 && @player2 ? get_matchup_data(@player1.id, @player2.id) : nil
    @player2_matchup_data = @player2 && @player1 ? get_matchup_data(@player2.id, @player1.id) : nil
  end
  
  def get_names
    @characters = Character.search(params[:search]).order("name asc")
  end
    
end

app/helpers/matchup_helper.rb
module MatchupHelper
end

app/views/matchup/_matchup.html.erb
<h3>Current Match</h3>
<h5>General Stats</h5>
<table class="table table-striped table-bordered table-hover">
  <thead>
   <tr>
      <th class="text">Name</th>
      <th>Win Rate</th>
      <th>Matches Played</th>
      <th>Matches Won</th>
      <th>Matches Lost</th>
    </tr> 
  </thead>
  <tbody>
    <% if @player1 %>
    <tr class="danger">
      <td><%= link_to @player1.name, @player1 %></td>
      <td><%= (@player1.win_rate * BigDecimal.new(100)).to_s + '%' %></td>
      <td><%= @player1.matches_played %></td>
      <td><%= @player1.matches_won %></td>
      <td><%= @player1.matches_lost %></td>
    </tr>
    <% else %>
      <% display_text = @player1_name ? @player1_name + " not recorded yet" : "Current match" %>
      <tr class="danger">
        <td><%= display_text %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    <% end %>
    <% if @player2 %>
    <tr class="info">
      <td><%= link_to @player2.name, @player2 %></td>
      <td><%= (@player2.win_rate * BigDecimal.new(100)).to_s + '%' %></td>
      <td><%= @player2.matches_played %></td>
      <td><%= @player2.matches_won %></td>
      <td><%= @player2.matches_lost %></td>
    </tr>
    <% else %>
      <% display_text = @player2_name ? @player2_name + " not recorded yet" : "not recieved" %>
      <tr class="info">
        <td><%= display_text %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h5>Matchup Stats</h5>
<table class="table table-striped table-bordered table-hover">
  <thead>
   <tr>
      <th class="text">Opponent Name</th>
      <th>Win Rate Against</th>
      <th>Matches Played With</th>
      <th>Matches Won Against</th>
      <th>Matches Lost To</th>
    </tr> 
  </thead>
  <tbody>
    <% data_exists = @player1_matchup_data && @player2_matchup_data %>
      <% if data_exists %>
        <% p1_opponent_data, p2_opponent_data = {} %>
        <% @player1_matchup_data.each_key do |opponent_id| %>
          <% p1_opponent_data =  @player1_matchup_data[opponent_id] %>
          <% p1_opponent_data[:id] = opponent_id %>
        <% end %>
        <% @player2_matchup_data.each_key do |opponent_id| %>
          <% p2_opponent_data =  @player2_matchup_data[opponent_id] %>
          <% p2_opponent_data[:id] = opponent_id %>
        <% end %>
        <tr class="danger">
          <td><%= link_to p2_opponent_data[:name], '/characters/' + p2_opponent_data[:id].to_s %></td>
          <td><%= (p1_opponent_data[:win_rate] * BigDecimal.new(100)).to_s + '%' %></td>
          <td><%= p1_opponent_data[:matches_played] %></td>
          <td><%= p1_opponent_data[:matches_won] %></td>
          <td><%= p1_opponent_data[:matches_lost] %></td>
        </tr>
        <tr class="info">
          <td><%= link_to p1_opponent_data[:name], '/characters/' + p1_opponent_data[:id].to_s %></td>
          <td><%= (p2_opponent_data[:win_rate] * BigDecimal.new(100)).to_s + '%' %></td>
          <td><%= p2_opponent_data[:matches_played] %></td>
          <td><%= p2_opponent_data[:matches_won] %></td>
          <td><%= p2_opponent_data[:matches_lost] %></td>
        </tr>
      <% else %>
        <tr>
          <td>No matchup data available</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/matchup/get_matchup.js.erb
$("#current_match").html("<%= escape_javascript(render :partial => "matchup") %>");

app/views/matchup/get_names.js.erb
$("#current_match").html("<%= escape_javascript(render :partial => "matchup") %>");

app/views/matchup/index.html.erb
<h1>Matchup</h1>

<!--PUT IN CONDITIONAL FOR NOT HAVING RECIEVED CHARACTERS YET-->
<!--VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV-->

<!--<input type="text" name="player1" id="player1">-->
<!--<input type="text" name="player2" id="player2">-->

<%= autocomplete_field_tag :player1, params[:player1], matchup_autocomplete_character_name_path, {class: "search-query", placeholder: "", type: "search"} %> 
<%= autocomplete_field_tag :player2, params[:player2], matchup_autocomplete_character_name_path, {class: "search-query", placeholder: "", type: "search"} %> 
<button class="btn btn-primary" id="get_matchup">Get Matchup</button>

<div id="current_match"></div>